// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc3i9rITqUkzkYd6IDDGHwKZPfsr26go0',
    appId: '1:217717536609:android:1874486d1773432cbcb720',
    messagingSenderId: '217717536609',
    projectId: 'wbcconnect-8cd0a',
    storageBucket: 'wbcconnect-8cd0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvOVyureXdYFd34BsYyFE1s6i-XKRa9aM',
    appId: '1:217717536609:ios:31e3c8cba36e2e1abcb720',
    messagingSenderId: '217717536609',
    projectId: 'wbcconnect-8cd0a',
    storageBucket: 'wbcconnect-8cd0a.firebasestorage.app',
    androidClientId: '217717536609-16pqq20jvr3210sp8sntcehkbgja7pfb.apps.googleusercontent.com',
    iosClientId: '217717536609-jv8siip1821m9fl52dnoo9ehvheki4sk.apps.googleusercontent.com',
    iosBundleId: 'in.kagroup.finer.ios',
  );

}